import tkinter as tk
window = tk.Tk()
window.title("5 Questions")
window.geometry("800x350")
window.configure(background="purple")
score = 0
def inst():#Инструмент с помощью которого мы устанавливаем вариант того, что будем отвечать 1,2,3 или словом
    t = tk.Label(window, text="Все, что вам нужно сделать, это просто ответить на каждый вопрос «1, 2, 3» или словом")
    t.pack()

def start():
    def submit():
        print (ans.get())
        
    root = tk.Tk()
    root.title("question 1")
    root.configure(bg="brown")
    q = tk.Label(root, text="Where is Germany?")
    q.pack()
    a = tk.Label(root, text="1.)In Europe ")
    a.pack()
    b = tk.Label(root, text="2.)In Great Britain ")
    b.pack()
    c = tk.Label(root, text="3.)In Asia ")
    c.pack()
    ans = tk.Entry(root, width=40)
    ans.pack()
    sub = tk.Button(root, text="Submit", command=submit)
    sub.pack()
    print("Correct answer-1")
    root = tk.Tk()
    root.title("question 2")
    root.configure(bg="aqua")
    f = tk.Label(root, text="Where is England?")
    f.pack()
    g = tk.Label(root, text="1.)In Asia ")
    g.pack()
    h = tk.Label(root, text="2.)On an island")
    h.pack()
    j = tk.Label(root, text="3.)In the USA")
    j.pack()
    ans = tk.Entry(root, width=40)
    ans.pack()
    sub = tk.Button(root, text="Submit", command=submit)
    sub.pack()
    print("correct answer-2")
    root = tk.Tk()
    root.title("question 3")
    root.configure(bg="gold")
    global left
    h = tk.Label(root, text="What is the etymological meaning of antibiotics?")
    f.pack()
    h = tk.Label(root, text="1.)For Life")
    g.pack()
    o = tk.Label(root, text="2.)For Health")
    o.pack()
    v = tk.Label(root, text="3.)Against Live")
    v.pack()
    ans = tk.Entry(root, width=40)
    ans.pack()
    sub = tk.Button(root, text="Submit", command=submit)
    sub.pack()
    print("correct answer-3")
    root = tk.Tk()
    root.title("question 4")
    root.configure(bg="lightblue")
    global right
    l = tk.Label(root, text="Portability is for people who can not write new programs." "From whom whis quote")
    l.pack()
    p = tk.Label(root, text="1.)Bill Gates")
    p.pack()
    w = tk.Label(root, text="2.)Hillary Clinton")
    w.pack()
    r = tk.Label(root, text="3.)Richard Stallman")
    r.pack()
    t = tk.Label(root, text="4.)Linus Torvalds")
    t.pack()
    ans = tk.Entry(root, width=40)
    ans.pack()
    sub = tk.Button(root, text="Submit", command=submit)
    sub.pack()
    print("correct answer-4")
    root = tk.Tk()
    root.title("question 5")
    root.configure(bg="lime")
    s = tk.Label(root, text="Who is the richest man in the world?")
    s.pack()
    d = tk.Label(root, text="1.)Jeff Bezos")
    d.pack()
    m = tk.Label(root, text="2.)Bill Gates")
    m.pack()
    e = tk.Label(root, text="3.)Donald Trump")
    e.pack()
    ans = tk.Entry(root, width=40)
    ans.pack()
    sub = tk.Button(root, text="Submit", command=submit)
    sub.pack()
    print("correct answer-3")



greet = tk.Label(window,height=3,width=50,fg="lime", bg="purple",text="Добро пожаловать в мой опросник из 5 вопросов")
greet.pack()
startButton = tk.Button(window,height=3,width=12,  command=start,bg="pink",fg="blue", text="Start")
startButton.pack()
instr = tk.Button(window,height=3,width=12, text="Instructions",bg="cyan",fg="coral", command=inst)
instr.pack()
Color=tk.Button(window,height=3,width=12,bg="green",text="Color",command=lambda:window.config(bg="orange"))
Color.pack()
Button=tk.Button(window,height=3,width=12,bg="coral",text="Screen resolution",command=lambda:window.geometry("1000x700"))
Button.pack()
end = tk.Button(window, text="Exit",bg="brown", height=3,width=12, command=quit)
end.pack()

window.mainloop()
